export const GOOGLE_AUTH = 'google.auth'
export const GOOGLE_AUTH_SUCCESS = 'google.auth.success'
export const GOOGLE_AUTH_FAILED = 'google.auth.failed'

export const GOOGLE_LOAD_GMAIL = 'google.load.gmail'
export const GOOGLE_LOAD_GMAIL_SUCCESS = 'google.load.gmail.success'
export const GOOGLE_LOAD_GMAIL_FAILED = 'google.load.gmail.failed'
export const GOOGLE_FETCH_EMAILS = 'google.fetch.emails'
export const GOOGLE_FETCH_EMAILS_SUCCESS = 'google.fetch.emails.success'
export const GOOGLE_FETCH_EMAILS_FAILED = 'google.fetch.emails.failed'

export const GOOGLE_SEND_EMAIL = 'google.send.email'
export const GOOGLE_SEND_EMAIL_SUCCESS = 'google.send.email.success'
export const GOOGLE_SEND_EMAIL_FAILED = 'google.send.email.failed'

export const GOOGLE_LOAD_CALENDAR = 'google.load.calendar'
export const GOOGLE_LOAD_CALENDAR_SUCCESS = 'google.load.calendar.success'
export const GOOGLE_LOAD_CALENDAR_FAILED = 'google.load.calendar.failed'
export const GOOGLE_FETCH_EVENTS = 'google.fetch.events'
export const GOOGLE_FETCH_EVENTS_SUCCESS = 'google.fetch.events.success'
export const GOOGLE_FETCH_EVENTS_FAILED = 'google.fetch.events.failed'

export const GOOGLE_SEND_EVENT = 'google.send.event'
export const GOOGLE_SEND_EVENT_SUCCESS = 'google.send.event.success'
export const GOOGLE_SEND_EVENT_FAILED = 'google.send.event.failed'